title: "data/expedities"
description: "Journalistieke hackathons met CBS data"
url: "https://dataexpedities.nl"
baseurl: ""

permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - api
  - Dockerfile
  - docker-compose.yml
  - .env
  - .env.example
  - vendor

keep_files:
  - assets
